export const branchInputs = [
  {
    id: 1,
    name: 'branchName',
    type: 'text',
    placeholder: 'name',
    label: 'Name',
    pattern: '^[A-Za-z0-9 ]{3,50}$',
    required: true,
  },
  {
    id: 2,
    name: 'city',
    type: 'text',
    placeholder: 'city',
    label: 'City',
    required: true,
  },
  {
    id: 3,
    name: 'address',
    type: 'text',
    placeholder: 'address',
    label: 'Address',
    required: true,
  },
  {
    id: 4,
    name: 'description',
    type: 'text',
    placeholder: 'description',
    label: 'Description',
    required: true,
  },
];
export const employeeInputs = [
  {
    id: 1,
    name: 'firstname',
    type: 'text',
    placeholder: 'First name',
    label: 'First Name',
    pattern: '^[A-Za-z0-9 ]{3,50}$',
    required: true,
  },
  {
    id: 2,
    name: 'lastname',
    type: 'text',
    placeholder: 'lastname',
    label: 'Last Name',
    pattern: '^[A-Za-z0-9 ]{3,50}$',
    required: true,
  },
  {
    id: 3,
    name: 'username',
    type: 'text',
    placeholder: 'username',
    label: 'User Name',
    required: true,
  },
  {
    id: 4,
    name: 'password',
    type: 'password',
    placeholder: 'password',
    label: 'Password',
    required: false,
  },
  {
    id: 5,
    name: 'description',
    type: 'text',
    placeholder: 'description',
    label: 'Description',
    required: true,
  },
];

export const branchProductInputs = [
  {
    id: 1,
    name: 'description',
    type: 'text',
    placeholder: 'Description',
    label: 'Description',
  },
  {
    id: 2,
    name: 'quantity',
    type: 'number',
    placeholder: 'quantity',
    label: 'Quantity',
    min: '1',
    required: true,
  },
  {
    id: 3,
    name: 'price',
    type: 'number',
    placeholder: 'price',
    label: 'Price',
    step: '0.1',
    min: '1',
  },
];
