version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: ewaiter-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ewaiter
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - 6000:5432
